git add .gitignore
git add LICENSE
git add README.md
git add docs/images/Screen001.png
git add docs/images/Screen002.png
git add docs/images/Screen003.png
git add docs/note.md
git add git_add.sh
git add pom.xml
git add src/main/java/jp/ac/nig/ddbj/webapp/dstextsearch/Application.java
git add src/main/java/jp/ac/nig/ddbj/webapp/dstextsearch/ConfigurationForTiles.java
git add src/main/java/jp/ac/nig/ddbj/webapp/dstextsearch/controller/MainController.java
git add src/main/java/jp/ac/nig/ddbj/webapp/dstextsearch/dao/ResultInfo.java
git add src/main/resources/application.properties
git add src/main/webapp/WEB-INF/tiles/layout/basic.jsp
git add src/main/webapp/WEB-INF/tiles/tiles.xml
git add src/main/webapp/WEB-INF/tiles/view/body/body.jsp
git add src/main/webapp/WEB-INF/tiles/view/body/greeting.jsp
git add src/main/webapp/WEB-INF/tiles/view/footer.jsp
git add src/main/webapp/WEB-INF/tiles/view/header.jsp
git add src/main/webapp/static/images/506708890-612x612.jpg
git add src/main/webapp/static/images/Link-icon.jpg
git add src/main/webapp/static/images/link_icon.png
git add src/main/webapp/static/index.html
git add src/test/java/jp/ac/nig/ddbj/webapp/dstextsearch/ApplicationTests.java
git add src/test/java/jp/ac/nig/ddbj/webapp/dstextsearch/TestConfigurtaion.java
git add volvox.gff3
git add git_add.sh
